export const LOAD_ADMIN = "LOAD_ADMIN";
export const LOGIN_ADMIN = "LOGIN_ADMIN";
export const FAIL_ADMIN = "FAIL_ADMIN";
export const CURRENT_ADMIN = "CURRENT_ADMIN";
export const LOGOUT_ADMIN = "LOGOUT_ADMIN";
export const EDIT_ADMINPASSWORD = "EDIT_ADMINPASSWORD";
export const CLEAR_SUCCESSADMIN = "CLEAR_SUCCESSADMIN";
export const CLEAR_ERRORSADMIN = "CLEAR_ERRORSADMIN";
