export const LOAD_CANDIDATURE = "LOAD_CANDIDATURE";
export const FAIL_CANDIDATURE = "FAIL_CANDIDATURE";
export const ADD_CANDIDATURE = "ADD_CANDIDATURE";
export const CLEAR_SUCCESSCANDIDATURE = "CLEAR_SUCCESSCANDIDATURE";
export const CLEAR_ERRORCANDIDATURE ="CLEAR_ERRORCANDIDATURE";
export const GET_CANDIDATURE = "GET_CANDIDATURE";
export const DELETE_CANDIDATURE = "DELETE_CANDIDATURE";
