export const LOAD_NEWSLETTER = "LOAD_NEWSLETTER";
export const FAIL_NEWSLETTER = "FAIL_NEWSLETTER";
export const ADD_NEWSLETTER = "ADD_NEWSLETTER";
export const CLEAR_SUCCESSNEWSLETTER = "CLEAR_SUCCESSNEWSLETTER";
export const CLEAR_ERRORNEWSLETTER ="CLEAR_ERRORNEWSLETTER";
export const GET_NEWSLETTERS = "GET_NEWSLETTERS";
export const DELETE_NEWSLETTER = "DELETE_NEWSLETTER";
