export const LOAD_OFFREDEMPLOI = "LOAD_OFFREDEMPLOI";
export const FAIL_OFFREDEMPLOI = "FAIL_OFFREDEMPLOI";
export const ADD_OFFREDEMPLOI = "ADD_OFFREDEMPLOI";
export const CLEAR_SUCCESSOFFREDEMPLOI = "CLEAR_SUCCESSOFFREDEMPLOI";
export const CLEAR_ERROROFFREDEMPLOI ="CLEAR_ERROROFFREDEMPLOI";
export const GET_OFFREDEMPLOI = "GET_OFFREDEMPLOI";
export const GET_ONEOFFREDEMPLOI= "GET_ONEOFFREDEMPLOI";
export const DELETE_OFFREDEMPLOI = "DELETE_OFFREDEMPLOI";
